#!/bin/bash

# requires:
# - SUBJ_NAME

if [ -z $SUBJ_NAME ]; then
	echo "SUBJ_NAME not defined..exiting"
	exit
fi

if [ -z $SESS_ID ]; then	SESS_ID=1; fi

SUBJECT_DIR=$SUBJECTS_DIR/$SUBJ_NAME/s$SESS_ID

if [ ! -d $SUBJECT_DIR ]; then echo "ERROR: subject dir ($SUBJECT_DIR) not present !!!.....exiting"; exit; fi

ROI_DIR=$SUBJECT_DIR/roi

T1_IMAGE_LABEL=m3DT1
T1_DIR=$SUBJECT_DIR/mpr
T1_DATA=$T1_DIR/$T1_IMAGE_LABEL
T1_BRAIN_DATA=$T1_DIR/$T1_IMAGE_LABEL"_brain"
T1_BRAIN_DATA_MASK=$T1_DIR/$T1_IMAGE_LABEL"_brain_mask"
FAST_DIR=$T1_DIR/fast
FIRST_DIR=$T1_DIR/first
SIENAX_DIR=$T1_DIR/$T1_IMAGE_LABEL"_sienax"
T1_SEGMENT_GM_PATH=$T1_DIR/c13DT1
T1_SEGMENT_WM_PATH=$T1_DIR/c23DT1
T1_SEGMENT_CSF_PATH=$T1_DIR/c33DT1
T1_SEGMENT_WM_BBR_PATH=$ROI_DIR/reg_t1/mask_t1_wmseg4bbr
T1_SEGMENT_WM_ERO_PATH=$ROI_DIR/reg_t1/mask_t1_wmseg4Nuisance
T1_SEGMENT_CSF_ERO_PATH=$ROI_DIR/reg_t1/mask_t1_csfseg4Nuisance



DTI_IMAGE_LABEL=dw
DTI_EC_IMAGE_LABEL=dw_aligned_m1
DTI_ROTATED_BVEC=dw_aligned.bvecs
DTI_BVEC=$SUBJ_NAME-dti.bvecs
DTI_BVAL=dw_aligned.bvals
DTI_DIR=$SUBJECT_DIR/dti
DTI_DATA=$DTI_DIR/$DTI_IMAGE_LABEL
DTI_FIT_LABEL=dti
BEDPOSTX_DIR=$DTI_DIR/bedpostx
PROBTRACKX_DIR=$DTI_DIR/probtrackx
TRACKVIS_DIR=$DTI_DIR/trackvis
TV_MATRICES_DIR=$DTI_DIR/tv_matrices
TRACKVIS_TRANSPOSED_BVECS=bvec_vert.txt

RS_IMAGE_LABEL=resting
RS_DIR=$SUBJECT_DIR/resting
RS_DATA=$RS_DIR/$RS_IMAGE_LABEL
SBFC_DIR=$RS_DIR/sbfc
RS_SERIES_DIR=$SBFC_DIR/series
RS_EXAMPLEFUNC=$ROI_DIR/reg_epi/example_func

RS_SERIES_CSF=$RS_SERIES_DIR/csf_ts
RS_SERIES_WM=$RS_SERIES_DIR/wm_ts

RS_FINAL_REGSTD_DIR=$RS_DIR/reg_standard
RS_FINAL_REGSTD_IMAGE=$RS_FINAL_REGSTD_DIR/filtered_func_data

RS_POST_PREPROCESS_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc"
RS_POST_AROMA_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc_aroma"
RS_POST_NUISANCE_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc_aroma_nuisance"
RS_POST_NUISANCE_MELODIC_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc_aroma_nuisance_melodic"
RS_POST_NUISANCE_STANDARD_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc_aroma_nuisance_standard"
RS_POST_NUISANCE_MELODIC_STANDARD_IMAGE_LABEL=$RS_IMAGE_LABEL"_preproc_aroma_nuisance_melodic_resting"

RS_REGSTD_DIR=$RS_DIR/resting.ica/reg_standard
RS_REGSTD_IMAGE=$RS_REGSTD_DIR/filtered_func_data
RS_REGSTD_DENOIS_DIR=$RS_DIR/resting.ica/reg_standard_denoised
RS_REGSTD_DENOIS_IMAGE=$RS_REGSTD_DENOIS_DIR/filtered_func_data

RS_AROMA_DIR=$RS_DIR/ica_aroma
RS_AROMA_IMAGE=$RS_AROMA_DIR/denoised_func_data_nonaggr
RS_REGSTD_AROMA_DIR=$RS_AROMA_DIR/reg_standard
RS_REGSTD_AROMA_IMAGE=$RS_REGSTD_AROMA_DIR/filtered_func_data


MC_PARAMS_DIR=$RS_DIR/$RS_IMAGE_LABEL.ica/mc
MC_ABS_DISPL=$MC_PARAMS_DIR/prefiltered_func_data_mcf_abs_mean.rms
MC_REL_DISPL=$MC_PARAMS_DIR/prefiltered_func_data_mcf_rel_mean.rms

DE_DIR=$SUBJECT_DIR/de
DP_IMAGE_LABEL=dp
DP_DATA=$DE_DIR/$DP_IMAGE_LABEL
DP_BRAIN_DATA=$DE_DIR/$DP_IMAGE_LABEL"_brain"

T2_IMAGE_LABEL=t2
T2_DATA=$DE_DIR/$T2_IMAGE_LABEL
T2_BRAIN_DATA=$DE_DIR/$T2_IMAGE_LABEL"_brain"




















