template_name=2x36als_longitudinal
TEMPLATE_MELODIC_IC=/media/alba/data/MRI/projects/ELA/group_analysis/melodic/group_templates/2x36als_longitudinal/melodic_IC.nii.gz
TEMPLATE_MASK_IMAGE=/media/alba/data/MRI/projects/ELA/group_analysis/melodic/group_templates/2x36als_longitudinal/mask.nii.gz
TEMPLATE_BG_IMAGE=/media/alba/data/MRI/projects/ELA/group_analysis/melodic/group_templates/2x36als_longitudinal/bg_image.nii.gz
TEMPLATE_STATS_FOLDER=/media/alba/data/MRI/projects/ELA/group_analysis/melodic/group_templates/2x36als_longitudinal/stats
TEMPLATE_MASK_FOLDER=/media/alba/data/MRI/projects/ELA/group_analysis/melodic/group_templates/2x36als_longitudinal/stats
str_pruning_ic_id=() # valid RSN: you must set their id values removing 1: if in the html is the 6th RSN, you must write 5!!!!!!
str_arr_IC_labels=()
declare -a arr_IC_labels=()
declare -a arr_pruning_ic_id=()
